# Generated by Django 3.2.25 on 2026-04-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0002_auto_20260414_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smru.branch'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smru.college'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smru.year'),
        ),
    ]
