# Generated by Django 3.2.25 on 2026-04-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0003_auto_20260414_2342'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Create new table with correct schema
            CREATE TABLE smru_loginactivity_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                login_time DATETIME NOT NULL,
                logout_time DATETIME NULL,
                ip_address VARCHAR(45) NOT NULL,
                user_agent TEXT NOT NULL,
                user_id INTEGER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE
            );
            
            -- Copy data from old table (only login records, map timestamp to login_time)
            INSERT INTO smru_loginactivity_new (id, login_time, ip_address, user_agent, user_id)
            SELECT id, timestamp, ip_address, user_agent, user_id 
            FROM smru_loginactivity 
            WHERE activity_type = 'login';
            
            -- Update logout_time for login records by finding corresponding logout records
            UPDATE smru_loginactivity_new 
            SET logout_time = (
                SELECT l2.timestamp 
                FROM smru_loginactivity l2 
                WHERE l2.activity_type = 'logout' 
                AND l2.user_id = smru_loginactivity_new.user_id 
                AND l2.timestamp > smru_loginactivity_new.login_time 
                ORDER BY l2.timestamp ASC 
                LIMIT 1
            );
            
            -- Drop old table
            DROP TABLE smru_loginactivity;
            
            -- Rename new table
            ALTER TABLE smru_loginactivity_new RENAME TO smru_loginactivity;
            
            -- Create index
            CREATE INDEX smru_loginactivity_user_id_idx ON smru_loginactivity (user_id);
            CREATE INDEX smru_loginactivity_login_time_idx ON smru_loginactivity (login_time);
            """,
            reverse_sql="""
            -- Reverse migration: recreate old table structure
            CREATE TABLE smru_loginactivity_old (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                activity_type VARCHAR(20) NOT NULL,
                timestamp DATETIME NOT NULL,
                ip_address VARCHAR(45) NOT NULL,
                user_agent VARCHAR(300) NOT NULL,
                notes TEXT NOT NULL,
                user_id INTEGER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE
            );
            
            -- Convert back to old format (this will lose logout_time data)
            INSERT INTO smru_loginactivity_old (id, activity_type, timestamp, ip_address, user_agent, notes, user_id)
            SELECT id, 'login', login_time, ip_address, user_agent, 'User logged in successfully', user_id 
            FROM smru_loginactivity;
            
            DROP TABLE smru_loginactivity;
            ALTER TABLE smru_loginactivity_old RENAME TO smru_loginactivity;
            """
        ),
    ]
