# Generated by Django 3.2.25 on 2026-04-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0005_auto_20260416_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='type',
            field=models.CharField(
                choices=[('engineering', 'Engineering'), ('medical', 'Medical')],
                default='engineering',
                max_length=20
            ),
        ),
    ]
