# Generated by Django 3.2.25 on 2026-05-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0006_add_college_type_field'),
    ]

    operations = [
    ]
