# Generated by Django 3.2.25 on 2026-05-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0007_fix_loginactivity_schema_sqlite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintcategory',
            name='type',
            field=models.CharField(choices=[('listed_college', 'For Listed Colleges'), ('other_college', 'For Other Colleges'), ('both', 'For Both Listed and Other Colleges')], max_length=20),
        ),
    ]
