# Generated by Django 3.2.25 on 2026-05-11 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smru', '0009_auto_20260509_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_reason', models.CharField(blank=True, max_length=100)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_at', models.DateTimeField(blank=True, null=True)),
                ('daily_login_count', models.PositiveIntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Account Locks',
            },
        ),
    ]
