# Generated by Django 3.2.25 on 2026-05-11 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smru', '0011_alter_userrole_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintperson',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
