# Generated by Django 3.2.25 on 2026-05-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0012_add_user_to_complaintperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
