# Generated by Django 3.2.25 on 2026-05-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0013_auto_20260512_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='hall_ticket_number',
        ),
    ]
