# Generated by Django 3.2.25 on 2026-05-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0014_remove_studentprofile_hall_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus_year',
            field=models.CharField(blank=True, help_text='Set the syllabus year for this subject notes, e.g. 2023-24.', max_length=50),
        ),
    ]
