# Generated by Django 3.2.25 on 2026-05-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0015_subject_syllabus_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('year', 'name', 'syllabus_year')},
        ),
    ]
