# Generated by Django 3.2.25 on 2026-05-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0016_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='smru.college'),
        ),
        migrations.AddField(
            model_name='event',
            name='target',
            field=models.CharField(choices=[('listed_colleges', 'Listed Colleges'), ('non_listed_colleges', 'Non Listed Colleges'), ('specific_college', 'Specific College')], default='listed_colleges', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='smru.college'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('listed_colleges', 'Listed Colleges'), ('non_listed_colleges', 'Non Listed Colleges'), ('specific_college', 'Specific College')], default='listed_colleges', max_length=30),
        ),
    ]
