# Generated by Django 3.2.25 on 2026-05-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0017_auto_20260516_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='target',
            field=models.CharField(choices=[('listed_colleges', 'Listed Colleges'), ('non_listed_colleges', 'Non Listed Colleges'), ('both_colleges', 'Listed and Non Listed Colleges'), ('specific_college', 'Specific College')], default='listed_colleges', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('listed_colleges', 'Listed Colleges'), ('non_listed_colleges', 'Non Listed Colleges'), ('both_colleges', 'Listed and Non Listed Colleges'), ('specific_college', 'Specific College')], default='listed_colleges', max_length=30),
        ),
    ]
