# Generated by assistant to add unlimited_access to UserAccountLock
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0028_auto_20260531_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountlock',
            name='unlimited_access',
            field=models.BooleanField(default=False),
        ),
    ]
