# Generated by Django 3.2.25 on 2026-06-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0022_add_reset_method'),
        ('smru', '0029_add_unlimited_access_useraccountlock'),
    ]

    operations = [
    ]
