# Generated by Django 3.2.25 on 2026-06-02 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smru', '0034_auto_20260601_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listedstudent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='signupverification',
            name='matched_student',
        ),
        migrations.AddField(
            model_name='excelimporthistory',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_excel_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excelimporthistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_imports', to='smru.branch'),
        ),
        migrations.AddField(
            model_name='excelimporthistory',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='excel_imports/'),
        ),
        migrations.AddField(
            model_name='excelimporthistory',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listedstudent',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_students_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listedstudent',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smru.branch'),
        ),
        migrations.AddField(
            model_name='listedstudent',
            name='import_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_students', to='smru.excelimporthistory'),
        ),
        migrations.AlterField(
            model_name='excelimporthistory',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='excelimporthistory',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='listedstudent',
            unique_together=set(),
        ),
    ]
