# Generated by Django 3.2.25 on 2026-06-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0035_auto_20260602_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapprovalrequest',
            name='first_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationapprovalrequest',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrationapprovalrequest',
            name='staff_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationapprovalrequest',
            name='staff_permissions_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrationapprovalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted (No Response)')], default='pending', max_length=20),
        ),
    ]
